### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [vincbeaulieu/AudioReportAI#3]
HELLO MAN...CONGRATULATIONS FOR YOUR AMAZING PROJECT!!!BUT COULD YOU PLEASE TELL ME STEP BY STEP WHAT I HAVE TO DO FOR USE YOUR AMAZING PROJECT?I AM NEW ON THIS AND I DONT KNOW!!!

**Comment by vincbeaulieu** [comment]
You can follow the steps listed on the Readme using a Terminal on MacOS or Linux, or on Windows using the Windows Subsystem for Linux [https://github.com/vincbeaulieu/AudioReportAI#-getting-started-execution-guide](Readme).

I will be posting a video on my Youtube on how to use the project. Once the video made, the link will be added to the Readme.

**Comment by KENPOKASMMA1982** [comment]
THANKS SO MUCHHHHHHHHHHHH
